version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - node -e "console.log('Running Node.js ' + process.version)"
      - echo Installing Yarn...
      - npm install yarn -g
      - npm install npm-cli-login -g
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm-cli-login login -u jtubman -p rraOO98X -e james.tubman@dbpixelhouse.com -r https://registry.dbpixelhouse.com
      - yarn
  build:
    commands:
      - echo Building...
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist