version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - node -e "console.log('Running Node.js ' + process.version)"
      - echo Installing Yarn...
      - npm install yarn -g
      - npm config set @gravit8-software:registry=https://npm.pkg.github.com
      - npm config set //npm.pkg.github.com/:_authToken={{resolve:secretsmanager:GitHubToken:SecretString:OAuthToken}}
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      - echo Building...
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
  