version: 0.2

phases:
  install:
    commands:
      - echo Installing latest Node ...
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
      - . ~/.nvm/nvm.sh
      - export NVM_DIR="$HOME/.nvm"
      -  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
      - nvm install node
      - node -e "console.log('Running Node.js ' + process.version)"
      - echo Installing Yarn...
      - npm install yarn -g
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      - echo Building...
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist