version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - node -e "console.log('Running Node.js ' + process.version)"
      - echo Installing Yarn...
      - npm install yarn -g
  pre_build:
    commands:
      - echo Installing dependencies...
       - echo "//registry.dbpixelhouse.com/:_authToken=pC4BshDu+z0r0d1kUonBdA==" > .npmrc
      - yarn
  build:
    commands:
      - echo Building...
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist